apiVersion: kc.customer.com/v1
kind: DataProduct

metadata:
  # The primary key for the Data Product in Knowledge Catalog. IMMUTABLE.
  id: sms-data-records

  # 'active' will create/update the DP. 'deleted' will remove it.
  state: active
  #state: deleted

  region: eu

spec:
  displayName: "PoC via script - SMS Data Records"

  description: >
    Raw, granular event data for SMS usage. Represents the Data Record (DR),
    an aggregated view of the underlying events. Each data record
    represents 1 SMS sent by a customer to a recipient handset.

  ownerEmails:
    - prabhaarya@google.com

  accessApprovalConfig:
    approverEmails:
      - prabhaarya@google.com

  # List the dbt model names. The sync script will resolve these to their
  assets:
    - dbtModel: sms_delivery_receipts_demo

  # --- All aspects, both custom and system, are defined here ---
  aspects:

    # OOB System Aspect for the main overview page
    overview:
      content: |
        <h2>Overview</h2>
        <p>Raw, granular event data for SMS usage. This represents Data Record (DR), an aggregated view events. Each data record represents 1 SMS sent by a customer to their client (mobile handset).</p>
        <h3>What questions can this data product answer?</h3>
        <ul>
          <li>Which messages failed, and to which countries.</li>
          <li>How many messages were sent by a customer, in which country, over which supplier, and what was the status of those messages.</li>
        </ul>

    # OOB System Aspect for recommended queries
    queries:
      userManaged: true # This must be true for user-provided queries
      queries:
        - description: "Recent SMS data records for Sweden, most recent first"
          sql: |
            SELECT *
            FROM {{ ref('sms_data_records') }}
            WHERE country_code_alpha_2 = 'SE'
            ORDER BY message_sent_at DESC
            LIMIT 10
          source: USER # This must be USER
        - description: "Failed messages by destination country"
          sql: |
            SELECT country_code_alpha_2, state, COUNT(*) AS message_count
            FROM {{ ref('sms_data_records') }}
            WHERE state = 'UNDELIVERABLE'
            GROUP BY country_code_alpha_2, state
            ORDER BY message_count DESC
          source: USER

    refresh-cadence:
      frequency: Daily
      refreshTime: "every day"
    # Your custom aspects
    custom-data-product-profile:
      custom-data-product-type: ENTERPRISE
      custom-domain: PRODUCT
      custom-external-references:
        - custom-document-type: DESIGN_DOC
          custom-document-link: https://SMS_DATA_RECORDS_DESIGN_DOC_LINK
        - custom-document-type: OTHER
          custom-document-link: https://SMS_DATA_RECORDS_OTHER_DOC_LINK
      custom-contacts:
        - custom-role: DATA_PRODUCT_OWNER
          custom-name: Prabha Arya
          custom-email-id: prabhaarya@google.com
        - custom-role: DATA_ENGINEER
          custom-name: Prabha Arya
          custom-email-id: prabhaarya@google.com

    custom-data-product-status:
      custom-lifecycle-status: IN_DEVELOPMENT
      custom-maturity-level: 1_FOUNDATIONAL
